// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/openauth/v1/groups.proto

package openauth_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Group represents a group/role in the system for organizing users and permissions
type Group struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the group
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Unique UUID for the group
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Unique name for the group
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Human-readable display name for the group
	DisplayName string `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Optional detailed description of the group
	Description *string `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Whether this is a system group (cannot be deleted)
	IsSystem bool `protobuf:"varint,6,opt,name=is_system,json=isSystem,proto3" json:"is_system,omitempty"`
	// Whether this is the default group for new users
	IsDefault bool `protobuf:"varint,7,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	// Timestamp when the group was created
	CreatedAt int64 `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Timestamp when the group was last updated
	UpdatedAt     int64 `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_groups_proto_rawDescGZIP(), []int{0}
}

func (x *Group) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Group) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Group) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Group) GetIsSystem() bool {
	if x != nil {
		return x.IsSystem
	}
	return false
}

func (x *Group) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *Group) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Group) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// CreateGroupRequest to create a new group
type CreateGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique name for the group
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Human-readable display name for the group
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Optional detailed description of the group
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Whether this is the default group for new users (optional, defaults to false)
	IsDefault     *bool `protobuf:"varint,4,opt,name=is_default,json=isDefault,proto3,oneof" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_groups_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateGroupRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateGroupRequest) GetIsDefault() bool {
	if x != nil && x.IsDefault != nil {
		return *x.IsDefault
	}
	return false
}

// CreateGroupResponse after successful group creation
type CreateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupResponse) Reset() {
	*x = CreateGroupResponse{}
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupResponse) ProtoMessage() {}

func (x *CreateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_groups_proto_rawDescGZIP(), []int{2}
}

func (x *CreateGroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *CreateGroupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetGroupRequest to get group by ID or name
type GetGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*GetGroupRequest_Id
	//	*GetGroupRequest_Uuid
	//	*GetGroupRequest_Name
	Identifier    isGetGroupRequest_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupRequest) Reset() {
	*x = GetGroupRequest{}
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequest) ProtoMessage() {}

func (x *GetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRequest.ProtoReflect.Descriptor instead.
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_groups_proto_rawDescGZIP(), []int{3}
}

func (x *GetGroupRequest) GetIdentifier() isGetGroupRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetGroupRequest) GetId() int64 {
	if x != nil {
		if x, ok := x.Identifier.(*GetGroupRequest_Id); ok {
			return x.Id
		}
	}
	return 0
}

func (x *GetGroupRequest) GetUuid() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetGroupRequest_Uuid); ok {
			return x.Uuid
		}
	}
	return ""
}

func (x *GetGroupRequest) GetName() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetGroupRequest_Name); ok {
			return x.Name
		}
	}
	return ""
}

type isGetGroupRequest_Identifier interface {
	isGetGroupRequest_Identifier()
}

type GetGroupRequest_Id struct {
	Id int64 `protobuf:"varint,1,opt,name=id,proto3,oneof"`
}

type GetGroupRequest_Uuid struct {
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3,oneof"`
}

type GetGroupRequest_Name struct {
	Name string `protobuf:"bytes,3,opt,name=name,proto3,oneof"`
}

func (*GetGroupRequest_Id) isGetGroupRequest_Identifier() {}

func (*GetGroupRequest_Uuid) isGetGroupRequest_Identifier() {}

func (*GetGroupRequest_Name) isGetGroupRequest_Identifier() {}

// GetGroupResponse
type GetGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupResponse) Reset() {
	*x = GetGroupResponse{}
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupResponse) ProtoMessage() {}

func (x *GetGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupResponse.ProtoReflect.Descriptor instead.
func (*GetGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_groups_proto_rawDescGZIP(), []int{4}
}

func (x *GetGroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

// UpdateGroupRequest to update group information
type UpdateGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier for the group to update
	//
	// Types that are valid to be assigned to Identifier:
	//
	//	*UpdateGroupRequest_Id
	//	*UpdateGroupRequest_Uuid
	//	*UpdateGroupRequest_Name
	Identifier isUpdateGroupRequest_Identifier `protobuf_oneof:"identifier"`
	// Optional new name for the group
	NewName *string `protobuf:"bytes,4,opt,name=new_name,json=newName,proto3,oneof" json:"new_name,omitempty"`
	// Optional new display name
	DisplayName *string `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	// Optional new description
	Description *string `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Optional new default status
	IsDefault     *bool `protobuf:"varint,7,opt,name=is_default,json=isDefault,proto3,oneof" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupRequest) Reset() {
	*x = UpdateGroupRequest{}
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupRequest) ProtoMessage() {}

func (x *UpdateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_groups_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateGroupRequest) GetIdentifier() isUpdateGroupRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *UpdateGroupRequest) GetId() int64 {
	if x != nil {
		if x, ok := x.Identifier.(*UpdateGroupRequest_Id); ok {
			return x.Id
		}
	}
	return 0
}

func (x *UpdateGroupRequest) GetUuid() string {
	if x != nil {
		if x, ok := x.Identifier.(*UpdateGroupRequest_Uuid); ok {
			return x.Uuid
		}
	}
	return ""
}

func (x *UpdateGroupRequest) GetName() string {
	if x != nil {
		if x, ok := x.Identifier.(*UpdateGroupRequest_Name); ok {
			return x.Name
		}
	}
	return ""
}

func (x *UpdateGroupRequest) GetNewName() string {
	if x != nil && x.NewName != nil {
		return *x.NewName
	}
	return ""
}

func (x *UpdateGroupRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UpdateGroupRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateGroupRequest) GetIsDefault() bool {
	if x != nil && x.IsDefault != nil {
		return *x.IsDefault
	}
	return false
}

type isUpdateGroupRequest_Identifier interface {
	isUpdateGroupRequest_Identifier()
}

type UpdateGroupRequest_Id struct {
	Id int64 `protobuf:"varint,1,opt,name=id,proto3,oneof"`
}

type UpdateGroupRequest_Uuid struct {
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3,oneof"`
}

type UpdateGroupRequest_Name struct {
	Name string `protobuf:"bytes,3,opt,name=name,proto3,oneof"`
}

func (*UpdateGroupRequest_Id) isUpdateGroupRequest_Identifier() {}

func (*UpdateGroupRequest_Uuid) isUpdateGroupRequest_Identifier() {}

func (*UpdateGroupRequest_Name) isUpdateGroupRequest_Identifier() {}

// UpdateGroupResponse
type UpdateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupResponse) Reset() {
	*x = UpdateGroupResponse{}
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupResponse) ProtoMessage() {}

func (x *UpdateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupResponse.ProtoReflect.Descriptor instead.
func (*UpdateGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_groups_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateGroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *UpdateGroupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// DeleteGroupRequest to delete a group
type DeleteGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*DeleteGroupRequest_Id
	//	*DeleteGroupRequest_Uuid
	//	*DeleteGroupRequest_Name
	Identifier    isDeleteGroupRequest_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupRequest) Reset() {
	*x = DeleteGroupRequest{}
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupRequest) ProtoMessage() {}

func (x *DeleteGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_groups_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteGroupRequest) GetIdentifier() isDeleteGroupRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *DeleteGroupRequest) GetId() int64 {
	if x != nil {
		if x, ok := x.Identifier.(*DeleteGroupRequest_Id); ok {
			return x.Id
		}
	}
	return 0
}

func (x *DeleteGroupRequest) GetUuid() string {
	if x != nil {
		if x, ok := x.Identifier.(*DeleteGroupRequest_Uuid); ok {
			return x.Uuid
		}
	}
	return ""
}

func (x *DeleteGroupRequest) GetName() string {
	if x != nil {
		if x, ok := x.Identifier.(*DeleteGroupRequest_Name); ok {
			return x.Name
		}
	}
	return ""
}

type isDeleteGroupRequest_Identifier interface {
	isDeleteGroupRequest_Identifier()
}

type DeleteGroupRequest_Id struct {
	Id int64 `protobuf:"varint,1,opt,name=id,proto3,oneof"`
}

type DeleteGroupRequest_Uuid struct {
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3,oneof"`
}

type DeleteGroupRequest_Name struct {
	Name string `protobuf:"bytes,3,opt,name=name,proto3,oneof"`
}

func (*DeleteGroupRequest_Id) isDeleteGroupRequest_Identifier() {}

func (*DeleteGroupRequest_Uuid) isDeleteGroupRequest_Identifier() {}

func (*DeleteGroupRequest_Name) isDeleteGroupRequest_Identifier() {}

// DeleteGroupResponse
type DeleteGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupResponse) Reset() {
	*x = DeleteGroupResponse{}
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupResponse) ProtoMessage() {}

func (x *DeleteGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupResponse.ProtoReflect.Descriptor instead.
func (*DeleteGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_groups_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteGroupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteGroupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ListGroupsRequest for listing groups with pagination and filtering
type ListGroupsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of groups to return (default: 10, max: 100)
	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Number of groups to skip (for pagination)
	Offset int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// Optional search query (searches name, display_name, description)
	Search *string `protobuf:"bytes,3,opt,name=search,proto3,oneof" json:"search,omitempty"`
	// Optional filter by system groups
	IsSystem *bool `protobuf:"varint,4,opt,name=is_system,json=isSystem,proto3,oneof" json:"is_system,omitempty"`
	// Optional filter by default groups
	IsDefault     *bool `protobuf:"varint,5,opt,name=is_default,json=isDefault,proto3,oneof" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsRequest) Reset() {
	*x = ListGroupsRequest{}
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsRequest) ProtoMessage() {}

func (x *ListGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_groups_proto_rawDescGZIP(), []int{9}
}

func (x *ListGroupsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListGroupsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListGroupsRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *ListGroupsRequest) GetIsSystem() bool {
	if x != nil && x.IsSystem != nil {
		return *x.IsSystem
	}
	return false
}

func (x *ListGroupsRequest) GetIsDefault() bool {
	if x != nil && x.IsDefault != nil {
		return *x.IsDefault
	}
	return false
}

// ListGroupsResponse
type ListGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	HasMore       bool                   `protobuf:"varint,5,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsResponse) Reset() {
	*x = ListGroupsResponse{}
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsResponse) ProtoMessage() {}

func (x *ListGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_groups_proto_rawDescGZIP(), []int{10}
}

func (x *ListGroupsResponse) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ListGroupsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListGroupsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListGroupsResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListGroupsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// AssignUserToGroupRequest to add a user to a group
type AssignUserToGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User identifier
	//
	// Types that are valid to be assigned to UserIdentifier:
	//
	//	*AssignUserToGroupRequest_UserId
	//	*AssignUserToGroupRequest_UserUuid
	UserIdentifier isAssignUserToGroupRequest_UserIdentifier `protobuf_oneof:"user_identifier"`
	// Group identifier
	//
	// Types that are valid to be assigned to GroupIdentifier:
	//
	//	*AssignUserToGroupRequest_GroupId
	//	*AssignUserToGroupRequest_GroupUuid
	//	*AssignUserToGroupRequest_GroupName
	GroupIdentifier isAssignUserToGroupRequest_GroupIdentifier `protobuf_oneof:"group_identifier"`
	// Optional expiration time for the group membership
	ExpiresAt     *int64 `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignUserToGroupRequest) Reset() {
	*x = AssignUserToGroupRequest{}
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignUserToGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignUserToGroupRequest) ProtoMessage() {}

func (x *AssignUserToGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignUserToGroupRequest.ProtoReflect.Descriptor instead.
func (*AssignUserToGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_groups_proto_rawDescGZIP(), []int{11}
}

func (x *AssignUserToGroupRequest) GetUserIdentifier() isAssignUserToGroupRequest_UserIdentifier {
	if x != nil {
		return x.UserIdentifier
	}
	return nil
}

func (x *AssignUserToGroupRequest) GetUserId() int64 {
	if x != nil {
		if x, ok := x.UserIdentifier.(*AssignUserToGroupRequest_UserId); ok {
			return x.UserId
		}
	}
	return 0
}

func (x *AssignUserToGroupRequest) GetUserUuid() string {
	if x != nil {
		if x, ok := x.UserIdentifier.(*AssignUserToGroupRequest_UserUuid); ok {
			return x.UserUuid
		}
	}
	return ""
}

func (x *AssignUserToGroupRequest) GetGroupIdentifier() isAssignUserToGroupRequest_GroupIdentifier {
	if x != nil {
		return x.GroupIdentifier
	}
	return nil
}

func (x *AssignUserToGroupRequest) GetGroupId() int64 {
	if x != nil {
		if x, ok := x.GroupIdentifier.(*AssignUserToGroupRequest_GroupId); ok {
			return x.GroupId
		}
	}
	return 0
}

func (x *AssignUserToGroupRequest) GetGroupUuid() string {
	if x != nil {
		if x, ok := x.GroupIdentifier.(*AssignUserToGroupRequest_GroupUuid); ok {
			return x.GroupUuid
		}
	}
	return ""
}

func (x *AssignUserToGroupRequest) GetGroupName() string {
	if x != nil {
		if x, ok := x.GroupIdentifier.(*AssignUserToGroupRequest_GroupName); ok {
			return x.GroupName
		}
	}
	return ""
}

func (x *AssignUserToGroupRequest) GetExpiresAt() int64 {
	if x != nil && x.ExpiresAt != nil {
		return *x.ExpiresAt
	}
	return 0
}

type isAssignUserToGroupRequest_UserIdentifier interface {
	isAssignUserToGroupRequest_UserIdentifier()
}

type AssignUserToGroupRequest_UserId struct {
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3,oneof"`
}

type AssignUserToGroupRequest_UserUuid struct {
	UserUuid string `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3,oneof"`
}

func (*AssignUserToGroupRequest_UserId) isAssignUserToGroupRequest_UserIdentifier() {}

func (*AssignUserToGroupRequest_UserUuid) isAssignUserToGroupRequest_UserIdentifier() {}

type isAssignUserToGroupRequest_GroupIdentifier interface {
	isAssignUserToGroupRequest_GroupIdentifier()
}

type AssignUserToGroupRequest_GroupId struct {
	GroupId int64 `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3,oneof"`
}

type AssignUserToGroupRequest_GroupUuid struct {
	GroupUuid string `protobuf:"bytes,4,opt,name=group_uuid,json=groupUuid,proto3,oneof"`
}

type AssignUserToGroupRequest_GroupName struct {
	GroupName string `protobuf:"bytes,5,opt,name=group_name,json=groupName,proto3,oneof"`
}

func (*AssignUserToGroupRequest_GroupId) isAssignUserToGroupRequest_GroupIdentifier() {}

func (*AssignUserToGroupRequest_GroupUuid) isAssignUserToGroupRequest_GroupIdentifier() {}

func (*AssignUserToGroupRequest_GroupName) isAssignUserToGroupRequest_GroupIdentifier() {}

// AssignUserToGroupResponse
type AssignUserToGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignUserToGroupResponse) Reset() {
	*x = AssignUserToGroupResponse{}
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignUserToGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignUserToGroupResponse) ProtoMessage() {}

func (x *AssignUserToGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignUserToGroupResponse.ProtoReflect.Descriptor instead.
func (*AssignUserToGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_groups_proto_rawDescGZIP(), []int{12}
}

func (x *AssignUserToGroupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AssignUserToGroupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// RemoveUserFromGroupRequest to remove a user from a group
type RemoveUserFromGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User identifier
	//
	// Types that are valid to be assigned to UserIdentifier:
	//
	//	*RemoveUserFromGroupRequest_UserId
	//	*RemoveUserFromGroupRequest_UserUuid
	UserIdentifier isRemoveUserFromGroupRequest_UserIdentifier `protobuf_oneof:"user_identifier"`
	// Group identifier
	//
	// Types that are valid to be assigned to GroupIdentifier:
	//
	//	*RemoveUserFromGroupRequest_GroupId
	//	*RemoveUserFromGroupRequest_GroupUuid
	//	*RemoveUserFromGroupRequest_GroupName
	GroupIdentifier isRemoveUserFromGroupRequest_GroupIdentifier `protobuf_oneof:"group_identifier"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RemoveUserFromGroupRequest) Reset() {
	*x = RemoveUserFromGroupRequest{}
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserFromGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserFromGroupRequest) ProtoMessage() {}

func (x *RemoveUserFromGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserFromGroupRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserFromGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_groups_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveUserFromGroupRequest) GetUserIdentifier() isRemoveUserFromGroupRequest_UserIdentifier {
	if x != nil {
		return x.UserIdentifier
	}
	return nil
}

func (x *RemoveUserFromGroupRequest) GetUserId() int64 {
	if x != nil {
		if x, ok := x.UserIdentifier.(*RemoveUserFromGroupRequest_UserId); ok {
			return x.UserId
		}
	}
	return 0
}

func (x *RemoveUserFromGroupRequest) GetUserUuid() string {
	if x != nil {
		if x, ok := x.UserIdentifier.(*RemoveUserFromGroupRequest_UserUuid); ok {
			return x.UserUuid
		}
	}
	return ""
}

func (x *RemoveUserFromGroupRequest) GetGroupIdentifier() isRemoveUserFromGroupRequest_GroupIdentifier {
	if x != nil {
		return x.GroupIdentifier
	}
	return nil
}

func (x *RemoveUserFromGroupRequest) GetGroupId() int64 {
	if x != nil {
		if x, ok := x.GroupIdentifier.(*RemoveUserFromGroupRequest_GroupId); ok {
			return x.GroupId
		}
	}
	return 0
}

func (x *RemoveUserFromGroupRequest) GetGroupUuid() string {
	if x != nil {
		if x, ok := x.GroupIdentifier.(*RemoveUserFromGroupRequest_GroupUuid); ok {
			return x.GroupUuid
		}
	}
	return ""
}

func (x *RemoveUserFromGroupRequest) GetGroupName() string {
	if x != nil {
		if x, ok := x.GroupIdentifier.(*RemoveUserFromGroupRequest_GroupName); ok {
			return x.GroupName
		}
	}
	return ""
}

type isRemoveUserFromGroupRequest_UserIdentifier interface {
	isRemoveUserFromGroupRequest_UserIdentifier()
}

type RemoveUserFromGroupRequest_UserId struct {
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3,oneof"`
}

type RemoveUserFromGroupRequest_UserUuid struct {
	UserUuid string `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3,oneof"`
}

func (*RemoveUserFromGroupRequest_UserId) isRemoveUserFromGroupRequest_UserIdentifier() {}

func (*RemoveUserFromGroupRequest_UserUuid) isRemoveUserFromGroupRequest_UserIdentifier() {}

type isRemoveUserFromGroupRequest_GroupIdentifier interface {
	isRemoveUserFromGroupRequest_GroupIdentifier()
}

type RemoveUserFromGroupRequest_GroupId struct {
	GroupId int64 `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3,oneof"`
}

type RemoveUserFromGroupRequest_GroupUuid struct {
	GroupUuid string `protobuf:"bytes,4,opt,name=group_uuid,json=groupUuid,proto3,oneof"`
}

type RemoveUserFromGroupRequest_GroupName struct {
	GroupName string `protobuf:"bytes,5,opt,name=group_name,json=groupName,proto3,oneof"`
}

func (*RemoveUserFromGroupRequest_GroupId) isRemoveUserFromGroupRequest_GroupIdentifier() {}

func (*RemoveUserFromGroupRequest_GroupUuid) isRemoveUserFromGroupRequest_GroupIdentifier() {}

func (*RemoveUserFromGroupRequest_GroupName) isRemoveUserFromGroupRequest_GroupIdentifier() {}

// RemoveUserFromGroupResponse
type RemoveUserFromGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserFromGroupResponse) Reset() {
	*x = RemoveUserFromGroupResponse{}
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserFromGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserFromGroupResponse) ProtoMessage() {}

func (x *RemoveUserFromGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserFromGroupResponse.ProtoReflect.Descriptor instead.
func (*RemoveUserFromGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_groups_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveUserFromGroupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveUserFromGroupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ListGroupUsersRequest to get all users in a group
type ListGroupUsersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Group identifier
	//
	// Types that are valid to be assigned to GroupIdentifier:
	//
	//	*ListGroupUsersRequest_GroupId
	//	*ListGroupUsersRequest_GroupUuid
	//	*ListGroupUsersRequest_GroupName
	GroupIdentifier isListGroupUsersRequest_GroupIdentifier `protobuf_oneof:"group_identifier"`
	// Pagination
	Limit         int32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32 `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupUsersRequest) Reset() {
	*x = ListGroupUsersRequest{}
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupUsersRequest) ProtoMessage() {}

func (x *ListGroupUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupUsersRequest.ProtoReflect.Descriptor instead.
func (*ListGroupUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_groups_proto_rawDescGZIP(), []int{15}
}

func (x *ListGroupUsersRequest) GetGroupIdentifier() isListGroupUsersRequest_GroupIdentifier {
	if x != nil {
		return x.GroupIdentifier
	}
	return nil
}

func (x *ListGroupUsersRequest) GetGroupId() int64 {
	if x != nil {
		if x, ok := x.GroupIdentifier.(*ListGroupUsersRequest_GroupId); ok {
			return x.GroupId
		}
	}
	return 0
}

func (x *ListGroupUsersRequest) GetGroupUuid() string {
	if x != nil {
		if x, ok := x.GroupIdentifier.(*ListGroupUsersRequest_GroupUuid); ok {
			return x.GroupUuid
		}
	}
	return ""
}

func (x *ListGroupUsersRequest) GetGroupName() string {
	if x != nil {
		if x, ok := x.GroupIdentifier.(*ListGroupUsersRequest_GroupName); ok {
			return x.GroupName
		}
	}
	return ""
}

func (x *ListGroupUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListGroupUsersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type isListGroupUsersRequest_GroupIdentifier interface {
	isListGroupUsersRequest_GroupIdentifier()
}

type ListGroupUsersRequest_GroupId struct {
	GroupId int64 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3,oneof"`
}

type ListGroupUsersRequest_GroupUuid struct {
	GroupUuid string `protobuf:"bytes,2,opt,name=group_uuid,json=groupUuid,proto3,oneof"`
}

type ListGroupUsersRequest_GroupName struct {
	GroupName string `protobuf:"bytes,3,opt,name=group_name,json=groupName,proto3,oneof"`
}

func (*ListGroupUsersRequest_GroupId) isListGroupUsersRequest_GroupIdentifier() {}

func (*ListGroupUsersRequest_GroupUuid) isListGroupUsersRequest_GroupIdentifier() {}

func (*ListGroupUsersRequest_GroupName) isListGroupUsersRequest_GroupIdentifier() {}

// ListGroupUsersResponse
type ListGroupUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*GroupUser           `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	HasMore       bool                   `protobuf:"varint,5,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupUsersResponse) Reset() {
	*x = ListGroupUsersResponse{}
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupUsersResponse) ProtoMessage() {}

func (x *ListGroupUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupUsersResponse.ProtoReflect.Descriptor instead.
func (*ListGroupUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_groups_proto_rawDescGZIP(), []int{16}
}

func (x *ListGroupUsersResponse) GetUsers() []*GroupUser {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListGroupUsersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListGroupUsersResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListGroupUsersResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListGroupUsersResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// GroupUser represents a user's membership in a group
type GroupUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email         *string                `protobuf:"bytes,4,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Name          *string                `protobuf:"bytes,5,opt,name=name,proto3,oneof" json:"name,omitempty"`
	ExpiresAt     *int64                 `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	AssignedAt    int64                  `protobuf:"varint,7,opt,name=assigned_at,json=assignedAt,proto3" json:"assigned_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupUser) Reset() {
	*x = GroupUser{}
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupUser) ProtoMessage() {}

func (x *GroupUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupUser.ProtoReflect.Descriptor instead.
func (*GroupUser) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_groups_proto_rawDescGZIP(), []int{17}
}

func (x *GroupUser) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupUser) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *GroupUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GroupUser) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *GroupUser) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *GroupUser) GetExpiresAt() int64 {
	if x != nil && x.ExpiresAt != nil {
		return *x.ExpiresAt
	}
	return 0
}

func (x *GroupUser) GetAssignedAt() int64 {
	if x != nil {
		return x.AssignedAt
	}
	return 0
}

// ListUserGroupsRequest to get all groups for a user
type ListUserGroupsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User identifier
	//
	// Types that are valid to be assigned to UserIdentifier:
	//
	//	*ListUserGroupsRequest_UserId
	//	*ListUserGroupsRequest_UserUuid
	UserIdentifier isListUserGroupsRequest_UserIdentifier `protobuf_oneof:"user_identifier"`
	// Pagination
	Limit         int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserGroupsRequest) Reset() {
	*x = ListUserGroupsRequest{}
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserGroupsRequest) ProtoMessage() {}

func (x *ListUserGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListUserGroupsRequest) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_groups_proto_rawDescGZIP(), []int{18}
}

func (x *ListUserGroupsRequest) GetUserIdentifier() isListUserGroupsRequest_UserIdentifier {
	if x != nil {
		return x.UserIdentifier
	}
	return nil
}

func (x *ListUserGroupsRequest) GetUserId() int64 {
	if x != nil {
		if x, ok := x.UserIdentifier.(*ListUserGroupsRequest_UserId); ok {
			return x.UserId
		}
	}
	return 0
}

func (x *ListUserGroupsRequest) GetUserUuid() string {
	if x != nil {
		if x, ok := x.UserIdentifier.(*ListUserGroupsRequest_UserUuid); ok {
			return x.UserUuid
		}
	}
	return ""
}

func (x *ListUserGroupsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUserGroupsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type isListUserGroupsRequest_UserIdentifier interface {
	isListUserGroupsRequest_UserIdentifier()
}

type ListUserGroupsRequest_UserId struct {
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3,oneof"`
}

type ListUserGroupsRequest_UserUuid struct {
	UserUuid string `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3,oneof"`
}

func (*ListUserGroupsRequest_UserId) isListUserGroupsRequest_UserIdentifier() {}

func (*ListUserGroupsRequest_UserUuid) isListUserGroupsRequest_UserIdentifier() {}

// ListUserGroupsResponse
type ListUserGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*UserGroup           `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	HasMore       bool                   `protobuf:"varint,5,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserGroupsResponse) Reset() {
	*x = ListUserGroupsResponse{}
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserGroupsResponse) ProtoMessage() {}

func (x *ListUserGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListUserGroupsResponse) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_groups_proto_rawDescGZIP(), []int{19}
}

func (x *ListUserGroupsResponse) GetGroups() []*UserGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ListUserGroupsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListUserGroupsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUserGroupsResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListUserGroupsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// UserGroup represents a group membership for a user
type UserGroup struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GroupId          int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupUuid        string                 `protobuf:"bytes,2,opt,name=group_uuid,json=groupUuid,proto3" json:"group_uuid,omitempty"`
	GroupName        string                 `protobuf:"bytes,3,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	GroupDisplayName string                 `protobuf:"bytes,4,opt,name=group_display_name,json=groupDisplayName,proto3" json:"group_display_name,omitempty"`
	GroupDescription *string                `protobuf:"bytes,5,opt,name=group_description,json=groupDescription,proto3,oneof" json:"group_description,omitempty"`
	IsSystem         bool                   `protobuf:"varint,6,opt,name=is_system,json=isSystem,proto3" json:"is_system,omitempty"`
	IsDefault        bool                   `protobuf:"varint,7,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	ExpiresAt        *int64                 `protobuf:"varint,8,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	AssignedAt       int64                  `protobuf:"varint,9,opt,name=assigned_at,json=assignedAt,proto3" json:"assigned_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserGroup) Reset() {
	*x = UserGroup{}
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGroup) ProtoMessage() {}

func (x *UserGroup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_groups_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGroup.ProtoReflect.Descriptor instead.
func (*UserGroup) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_groups_proto_rawDescGZIP(), []int{20}
}

func (x *UserGroup) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *UserGroup) GetGroupUuid() string {
	if x != nil {
		return x.GroupUuid
	}
	return ""
}

func (x *UserGroup) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *UserGroup) GetGroupDisplayName() string {
	if x != nil {
		return x.GroupDisplayName
	}
	return ""
}

func (x *UserGroup) GetGroupDescription() string {
	if x != nil && x.GroupDescription != nil {
		return *x.GroupDescription
	}
	return ""
}

func (x *UserGroup) GetIsSystem() bool {
	if x != nil {
		return x.IsSystem
	}
	return false
}

func (x *UserGroup) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *UserGroup) GetExpiresAt() int64 {
	if x != nil && x.ExpiresAt != nil {
		return *x.ExpiresAt
	}
	return 0
}

func (x *UserGroup) GetAssignedAt() int64 {
	if x != nil {
		return x.AssignedAt
	}
	return 0
}

var File_proto_openauth_v1_groups_proto protoreflect.FileDescriptor

const file_proto_openauth_v1_groups_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/openauth/v1/groups.proto\x12\x02v1\"\x93\x02\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1b\n" +
	"\tis_system\x18\x06 \x01(\bR\bisSystem\x12\x1d\n" +
	"\n" +
	"is_default\x18\a \x01(\bR\tisDefault\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAtB\x0e\n" +
	"\f_description\"\xb5\x01\n" +
	"\x12CreateGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\"\n" +
	"\n" +
	"is_default\x18\x04 \x01(\bH\x01R\tisDefault\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_is_default\"P\n" +
	"\x13CreateGroupResponse\x12\x1f\n" +
	"\x05group\x18\x01 \x01(\v2\t.v1.GroupR\x05group\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"]\n" +
	"\x0fGetGroupRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\x03H\x00R\x02id\x12\x14\n" +
	"\x04uuid\x18\x02 \x01(\tH\x00R\x04uuid\x12\x14\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04nameB\f\n" +
	"\n" +
	"identifier\"3\n" +
	"\x10GetGroupResponse\x12\x1f\n" +
	"\x05group\x18\x01 \x01(\v2\t.v1.GroupR\x05group\"\xb0\x02\n" +
	"\x12UpdateGroupRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\x03H\x00R\x02id\x12\x14\n" +
	"\x04uuid\x18\x02 \x01(\tH\x00R\x04uuid\x12\x14\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x12\x1e\n" +
	"\bnew_name\x18\x04 \x01(\tH\x01R\anewName\x88\x01\x01\x12&\n" +
	"\fdisplay_name\x18\x05 \x01(\tH\x02R\vdisplayName\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\x03R\vdescription\x88\x01\x01\x12\"\n" +
	"\n" +
	"is_default\x18\a \x01(\bH\x04R\tisDefault\x88\x01\x01B\f\n" +
	"\n" +
	"identifierB\v\n" +
	"\t_new_nameB\x0f\n" +
	"\r_display_nameB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_is_default\"P\n" +
	"\x13UpdateGroupResponse\x12\x1f\n" +
	"\x05group\x18\x01 \x01(\v2\t.v1.GroupR\x05group\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"`\n" +
	"\x12DeleteGroupRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\x03H\x00R\x02id\x12\x14\n" +
	"\x04uuid\x18\x02 \x01(\tH\x00R\x04uuid\x12\x14\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04nameB\f\n" +
	"\n" +
	"identifier\"I\n" +
	"\x13DeleteGroupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xcc\x01\n" +
	"\x11ListGroupsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x1b\n" +
	"\x06search\x18\x03 \x01(\tH\x00R\x06search\x88\x01\x01\x12 \n" +
	"\tis_system\x18\x04 \x01(\bH\x01R\bisSystem\x88\x01\x01\x12\"\n" +
	"\n" +
	"is_default\x18\x05 \x01(\bH\x02R\tisDefault\x88\x01\x01B\t\n" +
	"\a_searchB\f\n" +
	"\n" +
	"_is_systemB\r\n" +
	"\v_is_default\"\xa1\x01\n" +
	"\x12ListGroupsResponse\x12!\n" +
	"\x06groups\x18\x01 \x03(\v2\t.v1.GroupR\x06groups\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x12\x19\n" +
	"\bhas_more\x18\x05 \x01(\bR\ahasMore\"\x8d\x02\n" +
	"\x18AssignUserToGroupRequest\x12\x19\n" +
	"\auser_id\x18\x01 \x01(\x03H\x00R\x06userId\x12\x1d\n" +
	"\tuser_uuid\x18\x02 \x01(\tH\x00R\buserUuid\x12\x1b\n" +
	"\bgroup_id\x18\x03 \x01(\x03H\x01R\agroupId\x12\x1f\n" +
	"\n" +
	"group_uuid\x18\x04 \x01(\tH\x01R\tgroupUuid\x12\x1f\n" +
	"\n" +
	"group_name\x18\x05 \x01(\tH\x01R\tgroupName\x12\"\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x03H\x02R\texpiresAt\x88\x01\x01B\x11\n" +
	"\x0fuser_identifierB\x12\n" +
	"\x10group_identifierB\r\n" +
	"\v_expires_at\"O\n" +
	"\x19AssignUserToGroupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xdc\x01\n" +
	"\x1aRemoveUserFromGroupRequest\x12\x19\n" +
	"\auser_id\x18\x01 \x01(\x03H\x00R\x06userId\x12\x1d\n" +
	"\tuser_uuid\x18\x02 \x01(\tH\x00R\buserUuid\x12\x1b\n" +
	"\bgroup_id\x18\x03 \x01(\x03H\x01R\agroupId\x12\x1f\n" +
	"\n" +
	"group_uuid\x18\x04 \x01(\tH\x01R\tgroupUuid\x12\x1f\n" +
	"\n" +
	"group_name\x18\x05 \x01(\tH\x01R\tgroupNameB\x11\n" +
	"\x0fuser_identifierB\x12\n" +
	"\x10group_identifier\"Q\n" +
	"\x1bRemoveUserFromGroupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb8\x01\n" +
	"\x15ListGroupUsersRequest\x12\x1b\n" +
	"\bgroup_id\x18\x01 \x01(\x03H\x00R\agroupId\x12\x1f\n" +
	"\n" +
	"group_uuid\x18\x02 \x01(\tH\x00R\tgroupUuid\x12\x1f\n" +
	"\n" +
	"group_name\x18\x03 \x01(\tH\x00R\tgroupName\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offsetB\x12\n" +
	"\x10group_identifier\"\xa7\x01\n" +
	"\x16ListGroupUsersResponse\x12#\n" +
	"\x05users\x18\x01 \x03(\v2\r.v1.GroupUserR\x05users\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x12\x19\n" +
	"\bhas_more\x18\x05 \x01(\bR\ahasMore\"\xf8\x01\n" +
	"\tGroupUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x19\n" +
	"\x05email\x18\x04 \x01(\tH\x00R\x05email\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x05 \x01(\tH\x01R\x04name\x88\x01\x01\x12\"\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x03H\x02R\texpiresAt\x88\x01\x01\x12\x1f\n" +
	"\vassigned_at\x18\a \x01(\x03R\n" +
	"assignedAtB\b\n" +
	"\x06_emailB\a\n" +
	"\x05_nameB\r\n" +
	"\v_expires_at\"\x92\x01\n" +
	"\x15ListUserGroupsRequest\x12\x19\n" +
	"\auser_id\x18\x01 \x01(\x03H\x00R\x06userId\x12\x1d\n" +
	"\tuser_uuid\x18\x02 \x01(\tH\x00R\buserUuid\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offsetB\x11\n" +
	"\x0fuser_identifier\"\xa9\x01\n" +
	"\x16ListUserGroupsResponse\x12%\n" +
	"\x06groups\x18\x01 \x03(\v2\r.v1.UserGroupR\x06groups\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x12\x19\n" +
	"\bhas_more\x18\x05 \x01(\bR\ahasMore\"\xea\x02\n" +
	"\tUserGroup\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x1d\n" +
	"\n" +
	"group_uuid\x18\x02 \x01(\tR\tgroupUuid\x12\x1d\n" +
	"\n" +
	"group_name\x18\x03 \x01(\tR\tgroupName\x12,\n" +
	"\x12group_display_name\x18\x04 \x01(\tR\x10groupDisplayName\x120\n" +
	"\x11group_description\x18\x05 \x01(\tH\x00R\x10groupDescription\x88\x01\x01\x12\x1b\n" +
	"\tis_system\x18\x06 \x01(\bR\bisSystem\x12\x1d\n" +
	"\n" +
	"is_default\x18\a \x01(\bR\tisDefault\x12\"\n" +
	"\n" +
	"expires_at\x18\b \x01(\x03H\x01R\texpiresAt\x88\x01\x01\x12\x1f\n" +
	"\vassigned_at\x18\t \x01(\x03R\n" +
	"assignedAtB\x14\n" +
	"\x12_group_descriptionB\r\n" +
	"\v_expires_atB\x0fZ\r./openauth_v1b\x06proto3"

var (
	file_proto_openauth_v1_groups_proto_rawDescOnce sync.Once
	file_proto_openauth_v1_groups_proto_rawDescData []byte
)

func file_proto_openauth_v1_groups_proto_rawDescGZIP() []byte {
	file_proto_openauth_v1_groups_proto_rawDescOnce.Do(func() {
		file_proto_openauth_v1_groups_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_openauth_v1_groups_proto_rawDesc), len(file_proto_openauth_v1_groups_proto_rawDesc)))
	})
	return file_proto_openauth_v1_groups_proto_rawDescData
}

var file_proto_openauth_v1_groups_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_openauth_v1_groups_proto_goTypes = []any{
	(*Group)(nil),                       // 0: v1.Group
	(*CreateGroupRequest)(nil),          // 1: v1.CreateGroupRequest
	(*CreateGroupResponse)(nil),         // 2: v1.CreateGroupResponse
	(*GetGroupRequest)(nil),             // 3: v1.GetGroupRequest
	(*GetGroupResponse)(nil),            // 4: v1.GetGroupResponse
	(*UpdateGroupRequest)(nil),          // 5: v1.UpdateGroupRequest
	(*UpdateGroupResponse)(nil),         // 6: v1.UpdateGroupResponse
	(*DeleteGroupRequest)(nil),          // 7: v1.DeleteGroupRequest
	(*DeleteGroupResponse)(nil),         // 8: v1.DeleteGroupResponse
	(*ListGroupsRequest)(nil),           // 9: v1.ListGroupsRequest
	(*ListGroupsResponse)(nil),          // 10: v1.ListGroupsResponse
	(*AssignUserToGroupRequest)(nil),    // 11: v1.AssignUserToGroupRequest
	(*AssignUserToGroupResponse)(nil),   // 12: v1.AssignUserToGroupResponse
	(*RemoveUserFromGroupRequest)(nil),  // 13: v1.RemoveUserFromGroupRequest
	(*RemoveUserFromGroupResponse)(nil), // 14: v1.RemoveUserFromGroupResponse
	(*ListGroupUsersRequest)(nil),       // 15: v1.ListGroupUsersRequest
	(*ListGroupUsersResponse)(nil),      // 16: v1.ListGroupUsersResponse
	(*GroupUser)(nil),                   // 17: v1.GroupUser
	(*ListUserGroupsRequest)(nil),       // 18: v1.ListUserGroupsRequest
	(*ListUserGroupsResponse)(nil),      // 19: v1.ListUserGroupsResponse
	(*UserGroup)(nil),                   // 20: v1.UserGroup
}
var file_proto_openauth_v1_groups_proto_depIdxs = []int32{
	0,  // 0: v1.CreateGroupResponse.group:type_name -> v1.Group
	0,  // 1: v1.GetGroupResponse.group:type_name -> v1.Group
	0,  // 2: v1.UpdateGroupResponse.group:type_name -> v1.Group
	0,  // 3: v1.ListGroupsResponse.groups:type_name -> v1.Group
	17, // 4: v1.ListGroupUsersResponse.users:type_name -> v1.GroupUser
	20, // 5: v1.ListUserGroupsResponse.groups:type_name -> v1.UserGroup
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_openauth_v1_groups_proto_init() }
func file_proto_openauth_v1_groups_proto_init() {
	if File_proto_openauth_v1_groups_proto != nil {
		return
	}
	file_proto_openauth_v1_groups_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_openauth_v1_groups_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_openauth_v1_groups_proto_msgTypes[3].OneofWrappers = []any{
		(*GetGroupRequest_Id)(nil),
		(*GetGroupRequest_Uuid)(nil),
		(*GetGroupRequest_Name)(nil),
	}
	file_proto_openauth_v1_groups_proto_msgTypes[5].OneofWrappers = []any{
		(*UpdateGroupRequest_Id)(nil),
		(*UpdateGroupRequest_Uuid)(nil),
		(*UpdateGroupRequest_Name)(nil),
	}
	file_proto_openauth_v1_groups_proto_msgTypes[7].OneofWrappers = []any{
		(*DeleteGroupRequest_Id)(nil),
		(*DeleteGroupRequest_Uuid)(nil),
		(*DeleteGroupRequest_Name)(nil),
	}
	file_proto_openauth_v1_groups_proto_msgTypes[9].OneofWrappers = []any{}
	file_proto_openauth_v1_groups_proto_msgTypes[11].OneofWrappers = []any{
		(*AssignUserToGroupRequest_UserId)(nil),
		(*AssignUserToGroupRequest_UserUuid)(nil),
		(*AssignUserToGroupRequest_GroupId)(nil),
		(*AssignUserToGroupRequest_GroupUuid)(nil),
		(*AssignUserToGroupRequest_GroupName)(nil),
	}
	file_proto_openauth_v1_groups_proto_msgTypes[13].OneofWrappers = []any{
		(*RemoveUserFromGroupRequest_UserId)(nil),
		(*RemoveUserFromGroupRequest_UserUuid)(nil),
		(*RemoveUserFromGroupRequest_GroupId)(nil),
		(*RemoveUserFromGroupRequest_GroupUuid)(nil),
		(*RemoveUserFromGroupRequest_GroupName)(nil),
	}
	file_proto_openauth_v1_groups_proto_msgTypes[15].OneofWrappers = []any{
		(*ListGroupUsersRequest_GroupId)(nil),
		(*ListGroupUsersRequest_GroupUuid)(nil),
		(*ListGroupUsersRequest_GroupName)(nil),
	}
	file_proto_openauth_v1_groups_proto_msgTypes[17].OneofWrappers = []any{}
	file_proto_openauth_v1_groups_proto_msgTypes[18].OneofWrappers = []any{
		(*ListUserGroupsRequest_UserId)(nil),
		(*ListUserGroupsRequest_UserUuid)(nil),
	}
	file_proto_openauth_v1_groups_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_openauth_v1_groups_proto_rawDesc), len(file_proto_openauth_v1_groups_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_openauth_v1_groups_proto_goTypes,
		DependencyIndexes: file_proto_openauth_v1_groups_proto_depIdxs,
		MessageInfos:      file_proto_openauth_v1_groups_proto_msgTypes,
	}.Build()
	File_proto_openauth_v1_groups_proto = out.File
	file_proto_openauth_v1_groups_proto_goTypes = nil
	file_proto_openauth_v1_groups_proto_depIdxs = nil
}
