// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/openauth_common/ping.proto

package openauth_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on OOPingRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OOPingRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OOPingRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OOPingRequestMultiError, or
// nil if none found.
func (m *OOPingRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *OOPingRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	if len(errors) > 0 {
		return OOPingRequestMultiError(errors)
	}

	return nil
}

// OOPingRequestMultiError is an error wrapping multiple validation errors
// returned by OOPingRequest.ValidateAll() if the designated constraints
// aren't met.
type OOPingRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OOPingRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OOPingRequestMultiError) AllErrors() []error { return m }

// OOPingRequestValidationError is the validation error returned by
// OOPingRequest.Validate if the designated constraints aren't met.
type OOPingRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OOPingRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OOPingRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OOPingRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OOPingRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OOPingRequestValidationError) ErrorName() string { return "OOPingRequestValidationError" }

// Error satisfies the builtin error interface
func (e OOPingRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOOPingRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OOPingRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OOPingRequestValidationError{}

// Validate checks the field values on OOPingResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OOPingResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OOPingResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OOPingResponseMultiError,
// or nil if none found.
func (m *OOPingResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *OOPingResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	if len(errors) > 0 {
		return OOPingResponseMultiError(errors)
	}

	return nil
}

// OOPingResponseMultiError is an error wrapping multiple validation errors
// returned by OOPingResponse.ValidateAll() if the designated constraints
// aren't met.
type OOPingResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OOPingResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OOPingResponseMultiError) AllErrors() []error { return m }

// OOPingResponseValidationError is the validation error returned by
// OOPingResponse.Validate if the designated constraints aren't met.
type OOPingResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OOPingResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OOPingResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OOPingResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OOPingResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OOPingResponseValidationError) ErrorName() string { return "OOPingResponseValidationError" }

// Error satisfies the builtin error interface
func (e OOPingResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOOPingResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OOPingResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OOPingResponseValidationError{}
