// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/openauth/v1/users.proto

package openauth_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User represents a user account in the system
type User struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid                string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Username            string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email               *string                `protobuf:"bytes,4,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Phone               *string                `protobuf:"bytes,5,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	EmailVerified       bool                   `protobuf:"varint,6,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	PhoneVerified       bool                   `protobuf:"varint,7,opt,name=phone_verified,json=phoneVerified,proto3" json:"phone_verified,omitempty"`
	IsActive            bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsLocked            bool                   `protobuf:"varint,9,opt,name=is_locked,json=isLocked,proto3" json:"is_locked,omitempty"`
	FailedLoginAttempts int32                  `protobuf:"varint,10,opt,name=failed_login_attempts,json=failedLoginAttempts,proto3" json:"failed_login_attempts,omitempty"`
	LastLoginAt         *int64                 `protobuf:"varint,11,opt,name=last_login_at,json=lastLoginAt,proto3,oneof" json:"last_login_at,omitempty"`
	PasswordChangedAt   int64                  `protobuf:"varint,12,opt,name=password_changed_at,json=passwordChangedAt,proto3" json:"password_changed_at,omitempty"`
	CreatedAt           int64                  `protobuf:"varint,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           int64                  `protobuf:"varint,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_openauth_v1_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_users_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *User) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *User) GetPhoneVerified() bool {
	if x != nil {
		return x.PhoneVerified
	}
	return false
}

func (x *User) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *User) GetIsLocked() bool {
	if x != nil {
		return x.IsLocked
	}
	return false
}

func (x *User) GetFailedLoginAttempts() int32 {
	if x != nil {
		return x.FailedLoginAttempts
	}
	return 0
}

func (x *User) GetLastLoginAt() int64 {
	if x != nil && x.LastLoginAt != nil {
		return *x.LastLoginAt
	}
	return 0
}

func (x *User) GetPasswordChangedAt() int64 {
	if x != nil {
		return x.PasswordChangedAt
	}
	return 0
}

func (x *User) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *User) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// UserProfile represents extended user profile information
type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProfileName   *string                `protobuf:"bytes,4,opt,name=profile_name,json=profileName,proto3,oneof" json:"profile_name,omitempty"` // Name/label for this profile
	FirstName     *string                `protobuf:"bytes,5,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName      *string                `protobuf:"bytes,6,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	DisplayName   *string                `protobuf:"bytes,7,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	Bio           *string                `protobuf:"bytes,8,opt,name=bio,proto3,oneof" json:"bio,omitempty"`
	AvatarUrl     *string                `protobuf:"bytes,9,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	DateOfBirth   *int64                 `protobuf:"varint,10,opt,name=date_of_birth,json=dateOfBirth,proto3,oneof" json:"date_of_birth,omitempty"` // Unix timestamp
	Gender        *string                `protobuf:"bytes,11,opt,name=gender,proto3,oneof" json:"gender,omitempty"`
	Timezone      *string                `protobuf:"bytes,12,opt,name=timezone,proto3,oneof" json:"timezone,omitempty"`
	Locale        *string                `protobuf:"bytes,13,opt,name=locale,proto3,oneof" json:"locale,omitempty"`
	Country       *string                `protobuf:"bytes,14,opt,name=country,proto3,oneof" json:"country,omitempty"`
	City          *string                `protobuf:"bytes,15,opt,name=city,proto3,oneof" json:"city,omitempty"`
	Address       *string                `protobuf:"bytes,16,opt,name=address,proto3,oneof" json:"address,omitempty"`
	PostalCode    *string                `protobuf:"bytes,17,opt,name=postal_code,json=postalCode,proto3,oneof" json:"postal_code,omitempty"`
	WebsiteUrl    *string                `protobuf:"bytes,18,opt,name=website_url,json=websiteUrl,proto3,oneof" json:"website_url,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,19,opt,name=metadata,proto3" json:"metadata,omitempty"` // JSON metadata
	CreatedAt     int64                  `protobuf:"varint,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_proto_openauth_v1_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_users_proto_rawDescGZIP(), []int{1}
}

func (x *UserProfile) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserProfile) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UserProfile) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserProfile) GetProfileName() string {
	if x != nil && x.ProfileName != nil {
		return *x.ProfileName
	}
	return ""
}

func (x *UserProfile) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *UserProfile) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *UserProfile) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UserProfile) GetBio() string {
	if x != nil && x.Bio != nil {
		return *x.Bio
	}
	return ""
}

func (x *UserProfile) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *UserProfile) GetDateOfBirth() int64 {
	if x != nil && x.DateOfBirth != nil {
		return *x.DateOfBirth
	}
	return 0
}

func (x *UserProfile) GetGender() string {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return ""
}

func (x *UserProfile) GetTimezone() string {
	if x != nil && x.Timezone != nil {
		return *x.Timezone
	}
	return ""
}

func (x *UserProfile) GetLocale() string {
	if x != nil && x.Locale != nil {
		return *x.Locale
	}
	return ""
}

func (x *UserProfile) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *UserProfile) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *UserProfile) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *UserProfile) GetPostalCode() string {
	if x != nil && x.PostalCode != nil {
		return *x.PostalCode
	}
	return ""
}

func (x *UserProfile) GetWebsiteUrl() string {
	if x != nil && x.WebsiteUrl != nil {
		return *x.WebsiteUrl
	}
	return ""
}

func (x *UserProfile) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UserProfile) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *UserProfile) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// SignUpRequest for user registration - only authentication credentials
type SignUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         *string                `protobuf:"bytes,2,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Phone         *string                `protobuf:"bytes,3,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpRequest) Reset() {
	*x = SignUpRequest{}
	mi := &file_proto_openauth_v1_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpRequest) ProtoMessage() {}

func (x *SignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpRequest.ProtoReflect.Descriptor instead.
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_users_proto_rawDescGZIP(), []int{2}
}

func (x *SignUpRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SignUpRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *SignUpRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *SignUpRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// SignUpResponse after successful registration - only user data
type SignUpResponse struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	User                      *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Message                   string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	EmailVerificationRequired bool                   `protobuf:"varint,3,opt,name=email_verification_required,json=emailVerificationRequired,proto3" json:"email_verification_required,omitempty"`
	PhoneVerificationRequired bool                   `protobuf:"varint,4,opt,name=phone_verification_required,json=phoneVerificationRequired,proto3" json:"phone_verification_required,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *SignUpResponse) Reset() {
	*x = SignUpResponse{}
	mi := &file_proto_openauth_v1_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpResponse) ProtoMessage() {}

func (x *SignUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpResponse.ProtoReflect.Descriptor instead.
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_users_proto_rawDescGZIP(), []int{3}
}

func (x *SignUpResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *SignUpResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SignUpResponse) GetEmailVerificationRequired() bool {
	if x != nil {
		return x.EmailVerificationRequired
	}
	return false
}

func (x *SignUpResponse) GetPhoneVerificationRequired() bool {
	if x != nil {
		return x.PhoneVerificationRequired
	}
	return false
}

// VerifyEmailRequest for email verification
type VerifyEmailRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Email            string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	VerificationCode string                 `protobuf:"bytes,2,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VerifyEmailRequest) Reset() {
	*x = VerifyEmailRequest{}
	mi := &file_proto_openauth_v1_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEmailRequest) ProtoMessage() {}

func (x *VerifyEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEmailRequest.ProtoReflect.Descriptor instead.
func (*VerifyEmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_users_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerifyEmailRequest) GetVerificationCode() string {
	if x != nil {
		return x.VerificationCode
	}
	return ""
}

// VerifyPhoneRequest for phone verification
type VerifyPhoneRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Phone            string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	VerificationCode string                 `protobuf:"bytes,2,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VerifyPhoneRequest) Reset() {
	*x = VerifyPhoneRequest{}
	mi := &file_proto_openauth_v1_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPhoneRequest) ProtoMessage() {}

func (x *VerifyPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPhoneRequest.ProtoReflect.Descriptor instead.
func (*VerifyPhoneRequest) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_users_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyPhoneRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *VerifyPhoneRequest) GetVerificationCode() string {
	if x != nil {
		return x.VerificationCode
	}
	return ""
}

// VerificationResponse for verification operations
type VerificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verified      bool                   `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificationResponse) Reset() {
	*x = VerificationResponse{}
	mi := &file_proto_openauth_v1_users_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationResponse) ProtoMessage() {}

func (x *VerificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_users_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationResponse.ProtoReflect.Descriptor instead.
func (*VerificationResponse) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_users_proto_rawDescGZIP(), []int{6}
}

func (x *VerificationResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *VerificationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ResendVerificationRequest to resend verification codes
type ResendVerificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"` // email or phone
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`             // "email" or "phone"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResendVerificationRequest) Reset() {
	*x = ResendVerificationRequest{}
	mi := &file_proto_openauth_v1_users_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResendVerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResendVerificationRequest) ProtoMessage() {}

func (x *ResendVerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_users_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResendVerificationRequest.ProtoReflect.Descriptor instead.
func (*ResendVerificationRequest) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_users_proto_rawDescGZIP(), []int{7}
}

func (x *ResendVerificationRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *ResendVerificationRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// ResendVerificationResponse
type ResendVerificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sent          bool                   `protobuf:"varint,1,opt,name=sent,proto3" json:"sent,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // When the code expires
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResendVerificationResponse) Reset() {
	*x = ResendVerificationResponse{}
	mi := &file_proto_openauth_v1_users_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResendVerificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResendVerificationResponse) ProtoMessage() {}

func (x *ResendVerificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_users_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResendVerificationResponse.ProtoReflect.Descriptor instead.
func (*ResendVerificationResponse) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_users_proto_rawDescGZIP(), []int{8}
}

func (x *ResendVerificationResponse) GetSent() bool {
	if x != nil {
		return x.Sent
	}
	return false
}

func (x *ResendVerificationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResendVerificationResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// CheckUsernameRequest to check username availability
type CheckUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUsernameRequest) Reset() {
	*x = CheckUsernameRequest{}
	mi := &file_proto_openauth_v1_users_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUsernameRequest) ProtoMessage() {}

func (x *CheckUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_users_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUsernameRequest.ProtoReflect.Descriptor instead.
func (*CheckUsernameRequest) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_users_proto_rawDescGZIP(), []int{9}
}

func (x *CheckUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// CheckUsernameResponse
type CheckUsernameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Suggestions   []string               `protobuf:"bytes,3,rep,name=suggestions,proto3" json:"suggestions,omitempty"` // Alternative username suggestions if not available
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUsernameResponse) Reset() {
	*x = CheckUsernameResponse{}
	mi := &file_proto_openauth_v1_users_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUsernameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUsernameResponse) ProtoMessage() {}

func (x *CheckUsernameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_users_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUsernameResponse.ProtoReflect.Descriptor instead.
func (*CheckUsernameResponse) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_users_proto_rawDescGZIP(), []int{10}
}

func (x *CheckUsernameResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *CheckUsernameResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CheckUsernameResponse) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

// CheckEmailRequest to check email availability
type CheckEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckEmailRequest) Reset() {
	*x = CheckEmailRequest{}
	mi := &file_proto_openauth_v1_users_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEmailRequest) ProtoMessage() {}

func (x *CheckEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_users_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEmailRequest.ProtoReflect.Descriptor instead.
func (*CheckEmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_users_proto_rawDescGZIP(), []int{11}
}

func (x *CheckEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// CheckEmailResponse
type CheckEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckEmailResponse) Reset() {
	*x = CheckEmailResponse{}
	mi := &file_proto_openauth_v1_users_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEmailResponse) ProtoMessage() {}

func (x *CheckEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_users_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEmailResponse.ProtoReflect.Descriptor instead.
func (*CheckEmailResponse) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_users_proto_rawDescGZIP(), []int{12}
}

func (x *CheckEmailResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *CheckEmailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// CreateProfileRequest to create a new profile for a user
type CreateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`                // UUID of the user this profile belongs to
	ProfileName   *string                `protobuf:"bytes,2,opt,name=profile_name,json=profileName,proto3,oneof" json:"profile_name,omitempty"` // Name/label for this profile (e.g., "Personal", "Work", "Gaming")
	FirstName     *string                `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName      *string                `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	DisplayName   *string                `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	Bio           *string                `protobuf:"bytes,6,opt,name=bio,proto3,oneof" json:"bio,omitempty"`
	AvatarUrl     *string                `protobuf:"bytes,7,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	DateOfBirth   *int64                 `protobuf:"varint,8,opt,name=date_of_birth,json=dateOfBirth,proto3,oneof" json:"date_of_birth,omitempty"` // Unix timestamp
	Gender        *string                `protobuf:"bytes,9,opt,name=gender,proto3,oneof" json:"gender,omitempty"`
	Timezone      *string                `protobuf:"bytes,10,opt,name=timezone,proto3,oneof" json:"timezone,omitempty"`
	Locale        *string                `protobuf:"bytes,11,opt,name=locale,proto3,oneof" json:"locale,omitempty"`
	Country       *string                `protobuf:"bytes,12,opt,name=country,proto3,oneof" json:"country,omitempty"`
	City          *string                `protobuf:"bytes,13,opt,name=city,proto3,oneof" json:"city,omitempty"`
	Address       *string                `protobuf:"bytes,14,opt,name=address,proto3,oneof" json:"address,omitempty"`
	PostalCode    *string                `protobuf:"bytes,15,opt,name=postal_code,json=postalCode,proto3,oneof" json:"postal_code,omitempty"`
	WebsiteUrl    *string                `protobuf:"bytes,16,opt,name=website_url,json=websiteUrl,proto3,oneof" json:"website_url,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,17,opt,name=metadata,proto3" json:"metadata,omitempty"` // JSON metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileRequest) Reset() {
	*x = CreateProfileRequest{}
	mi := &file_proto_openauth_v1_users_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileRequest) ProtoMessage() {}

func (x *CreateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_users_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_users_proto_rawDescGZIP(), []int{13}
}

func (x *CreateProfileRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *CreateProfileRequest) GetProfileName() string {
	if x != nil && x.ProfileName != nil {
		return *x.ProfileName
	}
	return ""
}

func (x *CreateProfileRequest) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *CreateProfileRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *CreateProfileRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *CreateProfileRequest) GetBio() string {
	if x != nil && x.Bio != nil {
		return *x.Bio
	}
	return ""
}

func (x *CreateProfileRequest) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *CreateProfileRequest) GetDateOfBirth() int64 {
	if x != nil && x.DateOfBirth != nil {
		return *x.DateOfBirth
	}
	return 0
}

func (x *CreateProfileRequest) GetGender() string {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return ""
}

func (x *CreateProfileRequest) GetTimezone() string {
	if x != nil && x.Timezone != nil {
		return *x.Timezone
	}
	return ""
}

func (x *CreateProfileRequest) GetLocale() string {
	if x != nil && x.Locale != nil {
		return *x.Locale
	}
	return ""
}

func (x *CreateProfileRequest) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *CreateProfileRequest) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *CreateProfileRequest) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *CreateProfileRequest) GetPostalCode() string {
	if x != nil && x.PostalCode != nil {
		return *x.PostalCode
	}
	return ""
}

func (x *CreateProfileRequest) GetWebsiteUrl() string {
	if x != nil && x.WebsiteUrl != nil {
		return *x.WebsiteUrl
	}
	return ""
}

func (x *CreateProfileRequest) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// CreateProfileResponse
type CreateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *UserProfile           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileResponse) Reset() {
	*x = CreateProfileResponse{}
	mi := &file_proto_openauth_v1_users_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileResponse) ProtoMessage() {}

func (x *CreateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_users_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_users_proto_rawDescGZIP(), []int{14}
}

func (x *CreateProfileResponse) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *CreateProfileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ListUserProfilesRequest to get all profiles for a user
type ListUserProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserProfilesRequest) Reset() {
	*x = ListUserProfilesRequest{}
	mi := &file_proto_openauth_v1_users_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserProfilesRequest) ProtoMessage() {}

func (x *ListUserProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_users_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListUserProfilesRequest) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_users_proto_rawDescGZIP(), []int{15}
}

func (x *ListUserProfilesRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *ListUserProfilesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUserProfilesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// ListUserProfilesResponse
type ListUserProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*UserProfile         `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	HasMore       bool                   `protobuf:"varint,5,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserProfilesResponse) Reset() {
	*x = ListUserProfilesResponse{}
	mi := &file_proto_openauth_v1_users_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserProfilesResponse) ProtoMessage() {}

func (x *ListUserProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_users_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListUserProfilesResponse) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_users_proto_rawDescGZIP(), []int{16}
}

func (x *ListUserProfilesResponse) GetProfiles() []*UserProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

func (x *ListUserProfilesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListUserProfilesResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUserProfilesResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListUserProfilesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// UpdateProfileRequest to update a specific profile
type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileUuid   string                 `protobuf:"bytes,1,opt,name=profile_uuid,json=profileUuid,proto3" json:"profile_uuid,omitempty"` // UUID of the profile to update
	ProfileName   *string                `protobuf:"bytes,2,opt,name=profile_name,json=profileName,proto3,oneof" json:"profile_name,omitempty"`
	FirstName     *string                `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName      *string                `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	DisplayName   *string                `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	Bio           *string                `protobuf:"bytes,6,opt,name=bio,proto3,oneof" json:"bio,omitempty"`
	AvatarUrl     *string                `protobuf:"bytes,7,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	DateOfBirth   *int64                 `protobuf:"varint,8,opt,name=date_of_birth,json=dateOfBirth,proto3,oneof" json:"date_of_birth,omitempty"`
	Gender        *string                `protobuf:"bytes,9,opt,name=gender,proto3,oneof" json:"gender,omitempty"`
	Timezone      *string                `protobuf:"bytes,10,opt,name=timezone,proto3,oneof" json:"timezone,omitempty"`
	Locale        *string                `protobuf:"bytes,11,opt,name=locale,proto3,oneof" json:"locale,omitempty"`
	Country       *string                `protobuf:"bytes,12,opt,name=country,proto3,oneof" json:"country,omitempty"`
	City          *string                `protobuf:"bytes,13,opt,name=city,proto3,oneof" json:"city,omitempty"`
	Address       *string                `protobuf:"bytes,14,opt,name=address,proto3,oneof" json:"address,omitempty"`
	PostalCode    *string                `protobuf:"bytes,15,opt,name=postal_code,json=postalCode,proto3,oneof" json:"postal_code,omitempty"`
	WebsiteUrl    *string                `protobuf:"bytes,16,opt,name=website_url,json=websiteUrl,proto3,oneof" json:"website_url,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,17,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_proto_openauth_v1_users_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_users_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_users_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateProfileRequest) GetProfileUuid() string {
	if x != nil {
		return x.ProfileUuid
	}
	return ""
}

func (x *UpdateProfileRequest) GetProfileName() string {
	if x != nil && x.ProfileName != nil {
		return *x.ProfileName
	}
	return ""
}

func (x *UpdateProfileRequest) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *UpdateProfileRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *UpdateProfileRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UpdateProfileRequest) GetBio() string {
	if x != nil && x.Bio != nil {
		return *x.Bio
	}
	return ""
}

func (x *UpdateProfileRequest) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *UpdateProfileRequest) GetDateOfBirth() int64 {
	if x != nil && x.DateOfBirth != nil {
		return *x.DateOfBirth
	}
	return 0
}

func (x *UpdateProfileRequest) GetGender() string {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return ""
}

func (x *UpdateProfileRequest) GetTimezone() string {
	if x != nil && x.Timezone != nil {
		return *x.Timezone
	}
	return ""
}

func (x *UpdateProfileRequest) GetLocale() string {
	if x != nil && x.Locale != nil {
		return *x.Locale
	}
	return ""
}

func (x *UpdateProfileRequest) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *UpdateProfileRequest) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *UpdateProfileRequest) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *UpdateProfileRequest) GetPostalCode() string {
	if x != nil && x.PostalCode != nil {
		return *x.PostalCode
	}
	return ""
}

func (x *UpdateProfileRequest) GetWebsiteUrl() string {
	if x != nil && x.WebsiteUrl != nil {
		return *x.WebsiteUrl
	}
	return ""
}

func (x *UpdateProfileRequest) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// UpdateProfileResponse
type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *UserProfile           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_proto_openauth_v1_users_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_users_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_users_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateProfileResponse) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *UpdateProfileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// DeleteProfileRequest to delete a specific profile
type DeleteProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileUuid   string                 `protobuf:"bytes,1,opt,name=profile_uuid,json=profileUuid,proto3" json:"profile_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileRequest) Reset() {
	*x = DeleteProfileRequest{}
	mi := &file_proto_openauth_v1_users_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileRequest) ProtoMessage() {}

func (x *DeleteProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_users_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileRequest.ProtoReflect.Descriptor instead.
func (*DeleteProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_users_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteProfileRequest) GetProfileUuid() string {
	if x != nil {
		return x.ProfileUuid
	}
	return ""
}

// DeleteProfileResponse
type DeleteProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileResponse) Reset() {
	*x = DeleteProfileResponse{}
	mi := &file_proto_openauth_v1_users_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileResponse) ProtoMessage() {}

func (x *DeleteProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_users_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileResponse.ProtoReflect.Descriptor instead.
func (*DeleteProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_users_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteProfileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetUserRequest to get user by ID or username
type GetUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*GetUserRequest_Id
	//	*GetUserRequest_Uuid
	//	*GetUserRequest_Username
	//	*GetUserRequest_Email
	Identifier     isGetUserRequest_Identifier `protobuf_oneof:"identifier"`
	IncludeProfile bool                        `protobuf:"varint,5,opt,name=include_profile,json=includeProfile,proto3" json:"include_profile,omitempty"` // Whether to include profile information
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_proto_openauth_v1_users_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_users_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_users_proto_rawDescGZIP(), []int{21}
}

func (x *GetUserRequest) GetIdentifier() isGetUserRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetUserRequest) GetId() int64 {
	if x != nil {
		if x, ok := x.Identifier.(*GetUserRequest_Id); ok {
			return x.Id
		}
	}
	return 0
}

func (x *GetUserRequest) GetUuid() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetUserRequest_Uuid); ok {
			return x.Uuid
		}
	}
	return ""
}

func (x *GetUserRequest) GetUsername() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetUserRequest_Username); ok {
			return x.Username
		}
	}
	return ""
}

func (x *GetUserRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetUserRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *GetUserRequest) GetIncludeProfile() bool {
	if x != nil {
		return x.IncludeProfile
	}
	return false
}

type isGetUserRequest_Identifier interface {
	isGetUserRequest_Identifier()
}

type GetUserRequest_Id struct {
	Id int64 `protobuf:"varint,1,opt,name=id,proto3,oneof"`
}

type GetUserRequest_Uuid struct {
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3,oneof"`
}

type GetUserRequest_Username struct {
	Username string `protobuf:"bytes,3,opt,name=username,proto3,oneof"`
}

type GetUserRequest_Email struct {
	Email string `protobuf:"bytes,4,opt,name=email,proto3,oneof"`
}

func (*GetUserRequest_Id) isGetUserRequest_Identifier() {}

func (*GetUserRequest_Uuid) isGetUserRequest_Identifier() {}

func (*GetUserRequest_Username) isGetUserRequest_Identifier() {}

func (*GetUserRequest_Email) isGetUserRequest_Identifier() {}

// GetUserResponse
type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Profile       *UserProfile           `protobuf:"bytes,2,opt,name=profile,proto3,oneof" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_proto_openauth_v1_users_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_users_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_users_proto_rawDescGZIP(), []int{22}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetUserResponse) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// UpdateUserRequest to update user information
type UpdateUserRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Uuid     string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Username *string                `protobuf:"bytes,2,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Email    *string                `protobuf:"bytes,3,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Phone    *string                `protobuf:"bytes,4,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	IsActive *bool                  `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	// Profile updates
	FirstName     *string `protobuf:"bytes,6,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName      *string `protobuf:"bytes,7,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	DisplayName   *string `protobuf:"bytes,8,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	Bio           *string `protobuf:"bytes,9,opt,name=bio,proto3,oneof" json:"bio,omitempty"`
	AvatarUrl     *string `protobuf:"bytes,10,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	Timezone      *string `protobuf:"bytes,11,opt,name=timezone,proto3,oneof" json:"timezone,omitempty"`
	Locale        *string `protobuf:"bytes,12,opt,name=locale,proto3,oneof" json:"locale,omitempty"`
	Country       *string `protobuf:"bytes,13,opt,name=country,proto3,oneof" json:"country,omitempty"`
	City          *string `protobuf:"bytes,14,opt,name=city,proto3,oneof" json:"city,omitempty"`
	Address       *string `protobuf:"bytes,15,opt,name=address,proto3,oneof" json:"address,omitempty"`
	PostalCode    *string `protobuf:"bytes,16,opt,name=postal_code,json=postalCode,proto3,oneof" json:"postal_code,omitempty"`
	WebsiteUrl    *string `protobuf:"bytes,17,opt,name=website_url,json=websiteUrl,proto3,oneof" json:"website_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_proto_openauth_v1_users_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_users_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_users_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateUserRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdateUserRequest) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *UpdateUserRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

func (x *UpdateUserRequest) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *UpdateUserRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *UpdateUserRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UpdateUserRequest) GetBio() string {
	if x != nil && x.Bio != nil {
		return *x.Bio
	}
	return ""
}

func (x *UpdateUserRequest) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *UpdateUserRequest) GetTimezone() string {
	if x != nil && x.Timezone != nil {
		return *x.Timezone
	}
	return ""
}

func (x *UpdateUserRequest) GetLocale() string {
	if x != nil && x.Locale != nil {
		return *x.Locale
	}
	return ""
}

func (x *UpdateUserRequest) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *UpdateUserRequest) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *UpdateUserRequest) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *UpdateUserRequest) GetPostalCode() string {
	if x != nil && x.PostalCode != nil {
		return *x.PostalCode
	}
	return ""
}

func (x *UpdateUserRequest) GetWebsiteUrl() string {
	if x != nil && x.WebsiteUrl != nil {
		return *x.WebsiteUrl
	}
	return ""
}

// UpdateUserResponse
type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Profile       *UserProfile           `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_proto_openauth_v1_users_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_users_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_users_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UpdateUserResponse) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// ChangePasswordRequest to change user password
type ChangePasswordRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Uuid            string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	CurrentPassword string                 `protobuf:"bytes,2,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	NewPassword     string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_proto_openauth_v1_users_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_users_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_users_proto_rawDescGZIP(), []int{25}
}

func (x *ChangePasswordRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ChangePasswordRequest) GetCurrentPassword() string {
	if x != nil {
		return x.CurrentPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

// ChangePasswordResponse
type ChangePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResponse) Reset() {
	*x = ChangePasswordResponse{}
	mi := &file_proto_openauth_v1_users_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResponse) ProtoMessage() {}

func (x *ChangePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_users_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResponse.ProtoReflect.Descriptor instead.
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_users_proto_rawDescGZIP(), []int{26}
}

func (x *ChangePasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ChangePasswordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ListUsersRequest for listing users with pagination and filtering
type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Search        *string                `protobuf:"bytes,3,opt,name=search,proto3,oneof" json:"search,omitempty"`                                     // Search in username, email, first_name, last_name
	IsActive      *bool                  `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`                // Filter by active status
	EmailVerified *bool                  `protobuf:"varint,5,opt,name=email_verified,json=emailVerified,proto3,oneof" json:"email_verified,omitempty"` // Filter by email verification status
	PhoneVerified *bool                  `protobuf:"varint,6,opt,name=phone_verified,json=phoneVerified,proto3,oneof" json:"phone_verified,omitempty"` // Filter by phone verification status
	SortBy        *string                `protobuf:"bytes,7,opt,name=sort_by,json=sortBy,proto3,oneof" json:"sort_by,omitempty"`                       // Sort by field (username, email, created_at, etc.)
	SortOrder     *string                `protobuf:"bytes,8,opt,name=sort_order,json=sortOrder,proto3,oneof" json:"sort_order,omitempty"`              // asc or desc
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_proto_openauth_v1_users_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_users_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_users_proto_rawDescGZIP(), []int{27}
}

func (x *ListUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUsersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListUsersRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *ListUsersRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

func (x *ListUsersRequest) GetEmailVerified() bool {
	if x != nil && x.EmailVerified != nil {
		return *x.EmailVerified
	}
	return false
}

func (x *ListUsersRequest) GetPhoneVerified() bool {
	if x != nil && x.PhoneVerified != nil {
		return *x.PhoneVerified
	}
	return false
}

func (x *ListUsersRequest) GetSortBy() string {
	if x != nil && x.SortBy != nil {
		return *x.SortBy
	}
	return ""
}

func (x *ListUsersRequest) GetSortOrder() string {
	if x != nil && x.SortOrder != nil {
		return *x.SortOrder
	}
	return ""
}

// ListUsersResponse
type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	HasMore       bool                   `protobuf:"varint,5,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_proto_openauth_v1_users_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_users_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_users_proto_rawDescGZIP(), []int{28}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListUsersResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUsersResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListUsersResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// DeleteUserRequest to delete/deactivate user
type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	SoftDelete    bool                   `protobuf:"varint,2,opt,name=soft_delete,json=softDelete,proto3" json:"soft_delete,omitempty"` // If true, just deactivate; if false, hard delete
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_proto_openauth_v1_users_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_users_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_users_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteUserRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *DeleteUserRequest) GetSoftDelete() bool {
	if x != nil {
		return x.SoftDelete
	}
	return false
}

// DeleteUserResponse
type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_proto_openauth_v1_users_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openauth_v1_users_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_openauth_v1_users_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_openauth_v1_users_proto protoreflect.FileDescriptor

const file_proto_openauth_v1_users_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/openauth/v1/users.proto\x12\x02v1\"\xf5\x03\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x19\n" +
	"\x05email\x18\x04 \x01(\tH\x00R\x05email\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x05 \x01(\tH\x01R\x05phone\x88\x01\x01\x12%\n" +
	"\x0eemail_verified\x18\x06 \x01(\bR\remailVerified\x12%\n" +
	"\x0ephone_verified\x18\a \x01(\bR\rphoneVerified\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\x12\x1b\n" +
	"\tis_locked\x18\t \x01(\bR\bisLocked\x122\n" +
	"\x15failed_login_attempts\x18\n" +
	" \x01(\x05R\x13failedLoginAttempts\x12'\n" +
	"\rlast_login_at\x18\v \x01(\x03H\x02R\vlastLoginAt\x88\x01\x01\x12.\n" +
	"\x13password_changed_at\x18\f \x01(\x03R\x11passwordChangedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\x03R\tupdatedAtB\b\n" +
	"\x06_emailB\b\n" +
	"\x06_phoneB\x10\n" +
	"\x0e_last_login_at\"\xe8\x06\n" +
	"\vUserProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12&\n" +
	"\fprofile_name\x18\x04 \x01(\tH\x00R\vprofileName\x88\x01\x01\x12\"\n" +
	"\n" +
	"first_name\x18\x05 \x01(\tH\x01R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x06 \x01(\tH\x02R\blastName\x88\x01\x01\x12&\n" +
	"\fdisplay_name\x18\a \x01(\tH\x03R\vdisplayName\x88\x01\x01\x12\x15\n" +
	"\x03bio\x18\b \x01(\tH\x04R\x03bio\x88\x01\x01\x12\"\n" +
	"\n" +
	"avatar_url\x18\t \x01(\tH\x05R\tavatarUrl\x88\x01\x01\x12'\n" +
	"\rdate_of_birth\x18\n" +
	" \x01(\x03H\x06R\vdateOfBirth\x88\x01\x01\x12\x1b\n" +
	"\x06gender\x18\v \x01(\tH\aR\x06gender\x88\x01\x01\x12\x1f\n" +
	"\btimezone\x18\f \x01(\tH\bR\btimezone\x88\x01\x01\x12\x1b\n" +
	"\x06locale\x18\r \x01(\tH\tR\x06locale\x88\x01\x01\x12\x1d\n" +
	"\acountry\x18\x0e \x01(\tH\n" +
	"R\acountry\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\x0f \x01(\tH\vR\x04city\x88\x01\x01\x12\x1d\n" +
	"\aaddress\x18\x10 \x01(\tH\fR\aaddress\x88\x01\x01\x12$\n" +
	"\vpostal_code\x18\x11 \x01(\tH\rR\n" +
	"postalCode\x88\x01\x01\x12$\n" +
	"\vwebsite_url\x18\x12 \x01(\tH\x0eR\n" +
	"websiteUrl\x88\x01\x01\x12\x1a\n" +
	"\bmetadata\x18\x13 \x01(\fR\bmetadata\x12\x1d\n" +
	"\n" +
	"created_at\x18\x14 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x15 \x01(\x03R\tupdatedAtB\x0f\n" +
	"\r_profile_nameB\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_nameB\x0f\n" +
	"\r_display_nameB\x06\n" +
	"\x04_bioB\r\n" +
	"\v_avatar_urlB\x10\n" +
	"\x0e_date_of_birthB\t\n" +
	"\a_genderB\v\n" +
	"\t_timezoneB\t\n" +
	"\a_localeB\n" +
	"\n" +
	"\b_countryB\a\n" +
	"\x05_cityB\n" +
	"\n" +
	"\b_addressB\x0e\n" +
	"\f_postal_codeB\x0e\n" +
	"\f_website_url\"\x91\x01\n" +
	"\rSignUpRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x19\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05email\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x03 \x01(\tH\x01R\x05phone\x88\x01\x01\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpasswordB\b\n" +
	"\x06_emailB\b\n" +
	"\x06_phone\"\xc8\x01\n" +
	"\x0eSignUpResponse\x12\x1c\n" +
	"\x04user\x18\x01 \x01(\v2\b.v1.UserR\x04user\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12>\n" +
	"\x1bemail_verification_required\x18\x03 \x01(\bR\x19emailVerificationRequired\x12>\n" +
	"\x1bphone_verification_required\x18\x04 \x01(\bR\x19phoneVerificationRequired\"W\n" +
	"\x12VerifyEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12+\n" +
	"\x11verification_code\x18\x02 \x01(\tR\x10verificationCode\"W\n" +
	"\x12VerifyPhoneRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12+\n" +
	"\x11verification_code\x18\x02 \x01(\tR\x10verificationCode\"L\n" +
	"\x14VerificationResponse\x12\x1a\n" +
	"\bverified\x18\x01 \x01(\bR\bverified\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"O\n" +
	"\x19ResendVerificationRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"i\n" +
	"\x1aResendVerificationResponse\x12\x12\n" +
	"\x04sent\x18\x01 \x01(\bR\x04sent\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\"2\n" +
	"\x14CheckUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"q\n" +
	"\x15CheckUsernameResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\vsuggestions\x18\x03 \x03(\tR\vsuggestions\")\n" +
	"\x11CheckEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"L\n" +
	"\x12CheckEmailResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x93\x06\n" +
	"\x14CreateProfileRequest\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\x12&\n" +
	"\fprofile_name\x18\x02 \x01(\tH\x00R\vprofileName\x88\x01\x01\x12\"\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tH\x01R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x04 \x01(\tH\x02R\blastName\x88\x01\x01\x12&\n" +
	"\fdisplay_name\x18\x05 \x01(\tH\x03R\vdisplayName\x88\x01\x01\x12\x15\n" +
	"\x03bio\x18\x06 \x01(\tH\x04R\x03bio\x88\x01\x01\x12\"\n" +
	"\n" +
	"avatar_url\x18\a \x01(\tH\x05R\tavatarUrl\x88\x01\x01\x12'\n" +
	"\rdate_of_birth\x18\b \x01(\x03H\x06R\vdateOfBirth\x88\x01\x01\x12\x1b\n" +
	"\x06gender\x18\t \x01(\tH\aR\x06gender\x88\x01\x01\x12\x1f\n" +
	"\btimezone\x18\n" +
	" \x01(\tH\bR\btimezone\x88\x01\x01\x12\x1b\n" +
	"\x06locale\x18\v \x01(\tH\tR\x06locale\x88\x01\x01\x12\x1d\n" +
	"\acountry\x18\f \x01(\tH\n" +
	"R\acountry\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\r \x01(\tH\vR\x04city\x88\x01\x01\x12\x1d\n" +
	"\aaddress\x18\x0e \x01(\tH\fR\aaddress\x88\x01\x01\x12$\n" +
	"\vpostal_code\x18\x0f \x01(\tH\rR\n" +
	"postalCode\x88\x01\x01\x12$\n" +
	"\vwebsite_url\x18\x10 \x01(\tH\x0eR\n" +
	"websiteUrl\x88\x01\x01\x12\x1a\n" +
	"\bmetadata\x18\x11 \x01(\fR\bmetadataB\x0f\n" +
	"\r_profile_nameB\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_nameB\x0f\n" +
	"\r_display_nameB\x06\n" +
	"\x04_bioB\r\n" +
	"\v_avatar_urlB\x10\n" +
	"\x0e_date_of_birthB\t\n" +
	"\a_genderB\v\n" +
	"\t_timezoneB\t\n" +
	"\a_localeB\n" +
	"\n" +
	"\b_countryB\a\n" +
	"\x05_cityB\n" +
	"\n" +
	"\b_addressB\x0e\n" +
	"\f_postal_codeB\x0e\n" +
	"\f_website_url\"\\\n" +
	"\x15CreateProfileResponse\x12)\n" +
	"\aprofile\x18\x01 \x01(\v2\x0f.v1.UserProfileR\aprofile\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"d\n" +
	"\x17ListUserProfilesRequest\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\xb1\x01\n" +
	"\x18ListUserProfilesResponse\x12+\n" +
	"\bprofiles\x18\x01 \x03(\v2\x0f.v1.UserProfileR\bprofiles\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x12\x19\n" +
	"\bhas_more\x18\x05 \x01(\bR\ahasMore\"\x99\x06\n" +
	"\x14UpdateProfileRequest\x12!\n" +
	"\fprofile_uuid\x18\x01 \x01(\tR\vprofileUuid\x12&\n" +
	"\fprofile_name\x18\x02 \x01(\tH\x00R\vprofileName\x88\x01\x01\x12\"\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tH\x01R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x04 \x01(\tH\x02R\blastName\x88\x01\x01\x12&\n" +
	"\fdisplay_name\x18\x05 \x01(\tH\x03R\vdisplayName\x88\x01\x01\x12\x15\n" +
	"\x03bio\x18\x06 \x01(\tH\x04R\x03bio\x88\x01\x01\x12\"\n" +
	"\n" +
	"avatar_url\x18\a \x01(\tH\x05R\tavatarUrl\x88\x01\x01\x12'\n" +
	"\rdate_of_birth\x18\b \x01(\x03H\x06R\vdateOfBirth\x88\x01\x01\x12\x1b\n" +
	"\x06gender\x18\t \x01(\tH\aR\x06gender\x88\x01\x01\x12\x1f\n" +
	"\btimezone\x18\n" +
	" \x01(\tH\bR\btimezone\x88\x01\x01\x12\x1b\n" +
	"\x06locale\x18\v \x01(\tH\tR\x06locale\x88\x01\x01\x12\x1d\n" +
	"\acountry\x18\f \x01(\tH\n" +
	"R\acountry\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\r \x01(\tH\vR\x04city\x88\x01\x01\x12\x1d\n" +
	"\aaddress\x18\x0e \x01(\tH\fR\aaddress\x88\x01\x01\x12$\n" +
	"\vpostal_code\x18\x0f \x01(\tH\rR\n" +
	"postalCode\x88\x01\x01\x12$\n" +
	"\vwebsite_url\x18\x10 \x01(\tH\x0eR\n" +
	"websiteUrl\x88\x01\x01\x12\x1a\n" +
	"\bmetadata\x18\x11 \x01(\fR\bmetadataB\x0f\n" +
	"\r_profile_nameB\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_nameB\x0f\n" +
	"\r_display_nameB\x06\n" +
	"\x04_bioB\r\n" +
	"\v_avatar_urlB\x10\n" +
	"\x0e_date_of_birthB\t\n" +
	"\a_genderB\v\n" +
	"\t_timezoneB\t\n" +
	"\a_localeB\n" +
	"\n" +
	"\b_countryB\a\n" +
	"\x05_cityB\n" +
	"\n" +
	"\b_addressB\x0e\n" +
	"\f_postal_codeB\x0e\n" +
	"\f_website_url\"\\\n" +
	"\x15UpdateProfileResponse\x12)\n" +
	"\aprofile\x18\x01 \x01(\v2\x0f.v1.UserProfileR\aprofile\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"9\n" +
	"\x14DeleteProfileRequest\x12!\n" +
	"\fprofile_uuid\x18\x01 \x01(\tR\vprofileUuid\"K\n" +
	"\x15DeleteProfileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa5\x01\n" +
	"\x0eGetUserRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\x03H\x00R\x02id\x12\x14\n" +
	"\x04uuid\x18\x02 \x01(\tH\x00R\x04uuid\x12\x1c\n" +
	"\busername\x18\x03 \x01(\tH\x00R\busername\x12\x16\n" +
	"\x05email\x18\x04 \x01(\tH\x00R\x05email\x12'\n" +
	"\x0finclude_profile\x18\x05 \x01(\bR\x0eincludeProfileB\f\n" +
	"\n" +
	"identifier\"k\n" +
	"\x0fGetUserResponse\x12\x1c\n" +
	"\x04user\x18\x01 \x01(\v2\b.v1.UserR\x04user\x12.\n" +
	"\aprofile\x18\x02 \x01(\v2\x0f.v1.UserProfileH\x00R\aprofile\x88\x01\x01B\n" +
	"\n" +
	"\b_profile\"\xf7\x05\n" +
	"\x11UpdateUserRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1f\n" +
	"\busername\x18\x02 \x01(\tH\x00R\busername\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x03 \x01(\tH\x01R\x05email\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x04 \x01(\tH\x02R\x05phone\x88\x01\x01\x12 \n" +
	"\tis_active\x18\x05 \x01(\bH\x03R\bisActive\x88\x01\x01\x12\"\n" +
	"\n" +
	"first_name\x18\x06 \x01(\tH\x04R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\a \x01(\tH\x05R\blastName\x88\x01\x01\x12&\n" +
	"\fdisplay_name\x18\b \x01(\tH\x06R\vdisplayName\x88\x01\x01\x12\x15\n" +
	"\x03bio\x18\t \x01(\tH\aR\x03bio\x88\x01\x01\x12\"\n" +
	"\n" +
	"avatar_url\x18\n" +
	" \x01(\tH\bR\tavatarUrl\x88\x01\x01\x12\x1f\n" +
	"\btimezone\x18\v \x01(\tH\tR\btimezone\x88\x01\x01\x12\x1b\n" +
	"\x06locale\x18\f \x01(\tH\n" +
	"R\x06locale\x88\x01\x01\x12\x1d\n" +
	"\acountry\x18\r \x01(\tH\vR\acountry\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\x0e \x01(\tH\fR\x04city\x88\x01\x01\x12\x1d\n" +
	"\aaddress\x18\x0f \x01(\tH\rR\aaddress\x88\x01\x01\x12$\n" +
	"\vpostal_code\x18\x10 \x01(\tH\x0eR\n" +
	"postalCode\x88\x01\x01\x12$\n" +
	"\vwebsite_url\x18\x11 \x01(\tH\x0fR\n" +
	"websiteUrl\x88\x01\x01B\v\n" +
	"\t_usernameB\b\n" +
	"\x06_emailB\b\n" +
	"\x06_phoneB\f\n" +
	"\n" +
	"_is_activeB\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_nameB\x0f\n" +
	"\r_display_nameB\x06\n" +
	"\x04_bioB\r\n" +
	"\v_avatar_urlB\v\n" +
	"\t_timezoneB\t\n" +
	"\a_localeB\n" +
	"\n" +
	"\b_countryB\a\n" +
	"\x05_cityB\n" +
	"\n" +
	"\b_addressB\x0e\n" +
	"\f_postal_codeB\x0e\n" +
	"\f_website_url\"]\n" +
	"\x12UpdateUserResponse\x12\x1c\n" +
	"\x04user\x18\x01 \x01(\v2\b.v1.UserR\x04user\x12)\n" +
	"\aprofile\x18\x02 \x01(\v2\x0f.v1.UserProfileR\aprofile\"y\n" +
	"\x15ChangePasswordRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12)\n" +
	"\x10current_password\x18\x02 \x01(\tR\x0fcurrentPassword\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\"L\n" +
	"\x16ChangePasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xf3\x02\n" +
	"\x10ListUsersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x1b\n" +
	"\x06search\x18\x03 \x01(\tH\x00R\x06search\x88\x01\x01\x12 \n" +
	"\tis_active\x18\x04 \x01(\bH\x01R\bisActive\x88\x01\x01\x12*\n" +
	"\x0eemail_verified\x18\x05 \x01(\bH\x02R\remailVerified\x88\x01\x01\x12*\n" +
	"\x0ephone_verified\x18\x06 \x01(\bH\x03R\rphoneVerified\x88\x01\x01\x12\x1c\n" +
	"\asort_by\x18\a \x01(\tH\x04R\x06sortBy\x88\x01\x01\x12\"\n" +
	"\n" +
	"sort_order\x18\b \x01(\tH\x05R\tsortOrder\x88\x01\x01B\t\n" +
	"\a_searchB\f\n" +
	"\n" +
	"_is_activeB\x11\n" +
	"\x0f_email_verifiedB\x11\n" +
	"\x0f_phone_verifiedB\n" +
	"\n" +
	"\b_sort_byB\r\n" +
	"\v_sort_order\"\x9d\x01\n" +
	"\x11ListUsersResponse\x12\x1e\n" +
	"\x05users\x18\x01 \x03(\v2\b.v1.UserR\x05users\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x12\x19\n" +
	"\bhas_more\x18\x05 \x01(\bR\ahasMore\"H\n" +
	"\x11DeleteUserRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1f\n" +
	"\vsoft_delete\x18\x02 \x01(\bR\n" +
	"softDelete\"H\n" +
	"\x12DeleteUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB\x0fZ\r./openauth_v1b\x06proto3"

var (
	file_proto_openauth_v1_users_proto_rawDescOnce sync.Once
	file_proto_openauth_v1_users_proto_rawDescData []byte
)

func file_proto_openauth_v1_users_proto_rawDescGZIP() []byte {
	file_proto_openauth_v1_users_proto_rawDescOnce.Do(func() {
		file_proto_openauth_v1_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_openauth_v1_users_proto_rawDesc), len(file_proto_openauth_v1_users_proto_rawDesc)))
	})
	return file_proto_openauth_v1_users_proto_rawDescData
}

var file_proto_openauth_v1_users_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_proto_openauth_v1_users_proto_goTypes = []any{
	(*User)(nil),                       // 0: v1.User
	(*UserProfile)(nil),                // 1: v1.UserProfile
	(*SignUpRequest)(nil),              // 2: v1.SignUpRequest
	(*SignUpResponse)(nil),             // 3: v1.SignUpResponse
	(*VerifyEmailRequest)(nil),         // 4: v1.VerifyEmailRequest
	(*VerifyPhoneRequest)(nil),         // 5: v1.VerifyPhoneRequest
	(*VerificationResponse)(nil),       // 6: v1.VerificationResponse
	(*ResendVerificationRequest)(nil),  // 7: v1.ResendVerificationRequest
	(*ResendVerificationResponse)(nil), // 8: v1.ResendVerificationResponse
	(*CheckUsernameRequest)(nil),       // 9: v1.CheckUsernameRequest
	(*CheckUsernameResponse)(nil),      // 10: v1.CheckUsernameResponse
	(*CheckEmailRequest)(nil),          // 11: v1.CheckEmailRequest
	(*CheckEmailResponse)(nil),         // 12: v1.CheckEmailResponse
	(*CreateProfileRequest)(nil),       // 13: v1.CreateProfileRequest
	(*CreateProfileResponse)(nil),      // 14: v1.CreateProfileResponse
	(*ListUserProfilesRequest)(nil),    // 15: v1.ListUserProfilesRequest
	(*ListUserProfilesResponse)(nil),   // 16: v1.ListUserProfilesResponse
	(*UpdateProfileRequest)(nil),       // 17: v1.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),      // 18: v1.UpdateProfileResponse
	(*DeleteProfileRequest)(nil),       // 19: v1.DeleteProfileRequest
	(*DeleteProfileResponse)(nil),      // 20: v1.DeleteProfileResponse
	(*GetUserRequest)(nil),             // 21: v1.GetUserRequest
	(*GetUserResponse)(nil),            // 22: v1.GetUserResponse
	(*UpdateUserRequest)(nil),          // 23: v1.UpdateUserRequest
	(*UpdateUserResponse)(nil),         // 24: v1.UpdateUserResponse
	(*ChangePasswordRequest)(nil),      // 25: v1.ChangePasswordRequest
	(*ChangePasswordResponse)(nil),     // 26: v1.ChangePasswordResponse
	(*ListUsersRequest)(nil),           // 27: v1.ListUsersRequest
	(*ListUsersResponse)(nil),          // 28: v1.ListUsersResponse
	(*DeleteUserRequest)(nil),          // 29: v1.DeleteUserRequest
	(*DeleteUserResponse)(nil),         // 30: v1.DeleteUserResponse
}
var file_proto_openauth_v1_users_proto_depIdxs = []int32{
	0, // 0: v1.SignUpResponse.user:type_name -> v1.User
	1, // 1: v1.CreateProfileResponse.profile:type_name -> v1.UserProfile
	1, // 2: v1.ListUserProfilesResponse.profiles:type_name -> v1.UserProfile
	1, // 3: v1.UpdateProfileResponse.profile:type_name -> v1.UserProfile
	0, // 4: v1.GetUserResponse.user:type_name -> v1.User
	1, // 5: v1.GetUserResponse.profile:type_name -> v1.UserProfile
	0, // 6: v1.UpdateUserResponse.user:type_name -> v1.User
	1, // 7: v1.UpdateUserResponse.profile:type_name -> v1.UserProfile
	0, // 8: v1.ListUsersResponse.users:type_name -> v1.User
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_proto_openauth_v1_users_proto_init() }
func file_proto_openauth_v1_users_proto_init() {
	if File_proto_openauth_v1_users_proto != nil {
		return
	}
	file_proto_openauth_v1_users_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_openauth_v1_users_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_openauth_v1_users_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_openauth_v1_users_proto_msgTypes[13].OneofWrappers = []any{}
	file_proto_openauth_v1_users_proto_msgTypes[17].OneofWrappers = []any{}
	file_proto_openauth_v1_users_proto_msgTypes[21].OneofWrappers = []any{
		(*GetUserRequest_Id)(nil),
		(*GetUserRequest_Uuid)(nil),
		(*GetUserRequest_Username)(nil),
		(*GetUserRequest_Email)(nil),
	}
	file_proto_openauth_v1_users_proto_msgTypes[22].OneofWrappers = []any{}
	file_proto_openauth_v1_users_proto_msgTypes[23].OneofWrappers = []any{}
	file_proto_openauth_v1_users_proto_msgTypes[27].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_openauth_v1_users_proto_rawDesc), len(file_proto_openauth_v1_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_openauth_v1_users_proto_goTypes,
		DependencyIndexes: file_proto_openauth_v1_users_proto_depIdxs,
		MessageInfos:      file_proto_openauth_v1_users_proto_msgTypes,
	}.Build()
	File_proto_openauth_v1_users_proto = out.File
	file_proto_openauth_v1_users_proto_goTypes = nil
	file_proto_openauth_v1_users_proto_depIdxs = nil
}
