LogConfig: true
Logger:
  AppName: openauth
  Build: dev
  Level: debug
ConfigReader:
  Name: ""
  Format: ""
  Consul:
    Address: ""
    Token: ""
    Path: ""
  Zookeeper:
    Address: ""
    Path: ""
    Username: ""
    Password: ""
AppNames:
- HTTP_SERVER
- GRPC_SERVER
Server:
  GRPCPort: 8086
  HTTPPort: 8085
Repository:
  Name : memory
Service: {}