LogConfig: true
Logger:
  AppName: openauth
  Build: dev
  Level: debug
ConfigReader:
  Name: ""
  Format: ""
  Consul:
    Address: ""
    Token: ""
    Path: ""
AppNames:
# - SQL_MIGRATOR
- HTTP_SERVER
# - GRPC_SERVER
Server:
  HTTP:
    Port: 8085
    AuthenticationEnabled: false
  GRPC:
    Port: 8086
    AuthenticationEnabled: false
Repository:
  Name: Postgres
  Postgres:
    primary:
      Host: "localhost"
      Port: 5432
      Username: "admin"
      Password: OSwfiTlc1r5W7Z
      DBName: openauth
      SSLMode: "disable"
      MaxOpenConns: 0
      MaxIdleConns: 0
      ConnMaxLifetime: 0s
      ConnMaxIdleTime: 0s
    replica: []
Service:
  JWT:
    # JWT secret key for token signing - MUST be changed in production
    # Should be at least 32 characters long for HS256 algorithm
    SecretKey: "dev-jwt-secret-key-256-bits-long-for-development-environment-only-change-in-prod"
    AccessTokenTTL: "15m"   # Access token expiration time (15 minutes)
    RefreshTokenTTL: "168h"   # Refresh token expiration time (7 days)
  Security:
    BcryptCost: 12         # Password hashing cost (higher = more secure but slower)
    MaxLoginAttempts: 5    # Maximum failed login attempts before account lockout
    LockoutDuration: "30m" # Account lockout duration after max failed attempts
Debug:
  Enabled: true
  EnablePprof: true
Migrator:
  Path: "./resources/migrations/postgresql" # Path to the SQL migration files
  Action: up # Migration action (up/down/force/version)
  ForceVersion: 0 # Force version (optional)