LogConfig: true
Logger:
  AppName: openauth
  Build: dev
  Level: debug
ConfigReader:
  Name: ""
  Format: ""
  Consul:
    Address: ""
    Token: ""
    Path: ""
AppNames:
# - SQL_MIGRATOR
- HTTP_SERVER
# - GRPC_SERVER
Server:
  GRPCPort: 8086
  HTTPPort: 8085
Repository:
  Name: Postgres
  Postgres:
    primary:
      Host: "localhost"
      Port: 5432
      Username: "admin"
      Password: OSwfiTlc1r5W7Z
      DBName: openauth
      SSLMode: "disable"
      MaxOpenConns: 0
      MaxIdleConns: 0
      ConnMaxLifetime: 0s
      ConnMaxIdleTime: 0s
    replica: []
Service: {}
Debug:
  Enabled: true
  EnablePprof: true
Migrator:
  Path: "./resources/migrations/postgresql" # Path to the SQL migration files
  Action: up # Migration action (up/down/force/version)
  ForceVersion: 10 # Force version (optional)